"""
SCOPE — Template metadata schema.
Parsed from each template's template.yml via Pydantic.
"""
import re
from typing import Literal, Optional
from pydantic import BaseModel, Field, field_validator


class BrandingConfig(BaseModel):
    logo: Optional[str] = None
    primary_color: str = "#1a1a2e"
    accent_color: str = "#e94560"
    font_family: str = "Inter, sans-serif"
    report_header: str = "SCOPE Security Assessment"
    report_footer: str = "Generated by SCOPE"


class SeverityLabel(BaseModel):
    label: str
    color: str
    badge_color: str = "#fff"


class RenderConfig(BaseModel):
    page_size: Literal["A4", "Letter"] = "A4"
    orientation: Literal["portrait", "landscape"] = "portrait"
    include_toc: bool = True
    include_timestamps: bool = True
    include_severity_chart: bool = True
    date_format: str = "%Y-%m-%d %H:%M UTC"
    output_format: Literal["html"] = "html"


class TemplateSection(BaseModel):
    id: str
    title: str
    required: bool = False
    subsections: list[dict] = []


class TemplateMetadata(BaseModel):
    id: str
    name: str
    version: str = "1.0"
    description: str = ""
    template_type: Literal["report", "strategy", "both"] = "both"
    builtin: bool = False
    sections: list[TemplateSection] = []
    branding: BrandingConfig = Field(default_factory=BrandingConfig)
    severity_labels: dict[str, SeverityLabel] = {}
    disclaimer: str = ""
    render: RenderConfig = Field(default_factory=RenderConfig)

    @field_validator("id")
    @classmethod
    def id_must_be_slug(cls, v: str) -> str:
        if not re.match(r"^[a-z0-9][a-z0-9\-]*$", v):
            raise ValueError("Template id must be lowercase letters, digits, and hyphens only")
        return v
